import type { Metadata } from "next";
import SideBar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <div className="flex min-h-screen w-full flex-col">
      <Header/>
      <div className="mx-auto flex w-full max-w-7xl grow flex-col sm:flex-row sm:py-6">
        <SideBar/>
        {children}
      </div>
    </div>
  );
}
