import type { Metadata } from "next";
import SideBar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChampionshipsLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <div className="flex h-screen w-full flex-col overflow-hidden">
      <Header/>
      <div className="mx-auto flex w-full max-w-7xl h-[calc(100dvh-64px)] sm:py-8 flex-col sm:flex-row overflow-hidden">
        <SideBar/>
        {children}
      </div>
      <Toaster richColors position="top-center"/>
    </div>
  );
}
