import type { Metadata } from "next";
import SideBar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChampionshipsLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <div className="flex min-h-full w-full flex-col">
      <Header/>
      <div className="mx-auto flex min-w-0 max-w-7xl grow flex-col sm:flex-row sm:py-6">
        <SideBar/>
        {children}
      </div>
      <Toaster richColors position="top-center"/>
    </div>
  );
}
