import type { Metadata } from "next";
import SideBar from "@/components/layout/sidebar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChampionshipsLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <div>
      <SideBar/>
      {children}
      <Toaster richColors position="top-center"/>
    </div>
  );
}
