import type { Metadata } from "next";
import ChampionshipSideBar from "@/components/layout/championship-sidebar";
import ChampionshipHeader from "@/components/layout/championship-header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MyChampionshipLayout({ children, params }: { children: React.ReactNode; params: Promise<{ id: string }> }) {
  const { id } = await params;

  return (
    <div className="flex min-h-screen w-full flex-col">
      <ChampionshipHeader leagueId={id}/> 
      
      <div className="mx-auto flex w-full max-w-7xl grow flex-col sm:flex-row">
        <ChampionshipSideBar />
        {children}
      </div>
      <Toaster richColors position="top-center"/>
    </div>
  );
}